#DEV environment

app:
  message: This si the property file to the ${spring.application.root}

spring:
  datasource:
    driver-class-name=org.h2.Driver
    url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username=sa
    password=sa